# Mini Project - Classification of Wind Turbine Alarms
To start I will first look at the alarm data, and 1 quarter worth of data

In [30]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import warnings
warnings.simplefilter('ignore', DeprecationWarning)
%matplotlib inline
#pd.show_versions()

# path = 'C:\\Users\\kthomas\\Google Drive\\SMU\\DataMining\\MiniProject\\Data\\'
# path = '~/Documents/thomaskh522@gmail.com/SMU/DataMining/MiniProject/Data/'
# path = 'D:/Pattern/'
path = 'O:/wpshistory_LOGANSGAP/'

alarms_desc = pd.read_csv(path + "Siemens_Fault_Code_Descriptions.csv")
q1 = pd.read_csv(path + "SCADAcombined2017Q1.csv")
#q2 = pd.read_csv(path + "SCADAcombined2017Q2.csv")
#q3 = pd.read_csv(path + "SCADAcombined2017Q3.csv")
#q4 = pd.read_csv(path + "SCADAcombined2017Q4.csv")

In [31]:
# merge the alarms with the alarm descriptions
df = q1.merge(alarms_desc, 
         left_on = 'wtc_AlarmCde_endvalue', 
         right_on="Code",
         how='left')

df['TimeStamp'] = pd.to_datetime(df['TimeStamp'])
df.set_index('TimeStamp', inplace=True)
df.index

print(df.shape)
print(df.info())
df.head()

(1125182, 25)
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1125182 entries, 2017-01-02 15:30:00 to 2017-02-24 02:10:00
Data columns (total 25 columns):
Name                     1125182 non-null object
StationId                1125182 non-null int64
CommunicationId          1125182 non-null int64
NeighbourId              1125182 non-null int64
NeighbourIdTwo           1125182 non-null int64
XPos                     1125182 non-null int64
YPos                     1125182 non-null int64
wtc_GenRpm_mean          1124992 non-null float64
wtc_MainSRpm_mean        1124992 non-null float64
wtc_TwrHumid_mean        1124992 non-null float64
wtc_PowerRef_endvalue    1124993 non-null float64
wtc_PrWindSp_mean        1124992 non-null float64
wtc_NacelPos_mean        1124991 non-null float64
wtc_AmbieTmp_mean        1124991 non-null float64
wtc_GeOilTmp_mean        1124991 non-null float64
wtc_HubTemp_mean         1124991 non-null float64
wtc_NacelTmp_mean        1124991 non-null float64
wtc_ConvWTmp_mean        1124992 non-null float64
wtc_HydOilTm_mean        1124991 non-null float64
wtc_MainBTmp_mean        1124991 non-null float64
wtc_AlarmCde_endvalue    1124991 non-null object
wtc_ScInOper_timeon      1124991 non-null float64
Code                     1124210 non-null float64
Description              1124210 non-null object
Fault Type               1124210 non-null object
dtypes: float64(15), int64(6), object(4)
memory usage: 223.2+ MB
None

,Name,StationId,CommunicationId,NeighbourId,NeighbourIdTwo,XPos,YPos,wtc_GenRpm_mean,wtc_MainSRpm_mean,wtc_TwrHumid_mean,...,wtc_HubTemp_mean,wtc_NacelTmp_mean,wtc_ConvWTmp_mean,wtc_HydOilTm_mean,wtc_MainBTmp_mean,wtc_AlarmCde_endvalue,wtc_ScInOper_timeon,Code,Description,Fault Type
TimeStamp,,,,,,,,,,,,,,,,,,,,,
2017-01-02 15:30:00,T004,6,2308964,5,7,30,600,1355.321,14.96006,31.62146,...,20.00000,24.00000,31.53725,30.35122,38.00135,0,600.0,0.0,System faultless,W
2017-01-02 15:30:00,T007,9,2308967,8,10,1065,300,1207.784,13.33110,34.04166,...,18.87432,24.00000,29.08095,30.22913,40.00000,0,600.0,0.0,System faultless,W
2017-01-02 15:30:00,T010,12,2308970,11,13,1065,750,1049.281,11.58130,36.77564,...,20.00000,23.00000,29.94152,30.33175,36.98768,0,600.0,0.0,System faultless,W
2017-01-02 15:30:00,T017,19,2308977,20,21,30,1200,1261.156,13.92016,34.10806,...,19.00000,23.86940,30.26724,30.30332,39.00000,0,600.0,0.0,System faultless,W
2017-01-02 15:30:00,T020,22,2308980,21,20,30,1500,1061.441,11.71441,35.99195,...,17.00000,23.00992,30.10798,30.25607,38.00000,0,600.0,0.0,System faultless,W

In [29]:
# missing values by column
df.isnull().sum()

# drop columns that were missing values
#df.dropna(inplace=True)

Name                       0
StationId                  0
CommunicationId            0
NeighbourId                0
NeighbourIdTwo             0
XPos                       0
YPos                       0
wtc_GenRpm_mean          190
wtc_MainSRpm_mean        190
wtc_TwrHumid_mean        190
wtc_PowerRef_endvalue    189
wtc_PrWindSp_mean        190
wtc_NacelPos_mean        191
wtc_AmbieTmp_mean        191
wtc_GeOilTmp_mean        191
wtc_HubTemp_mean         191
wtc_NacelTmp_mean        191
wtc_ConvWTmp_mean        190
wtc_HydOilTm_mean        191
wtc_MainBTmp_mean        191
wtc_AlarmCde_endvalue    191
wtc_ScInOper_timeon      191
Code                     972
Description              972
Fault Type               972
dtype: int64

In [28]:
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
StationId,1125182.0,4.400838e+01,25.081895,1.000000e+00,2.200000e+01,4.400000e+01,6.600000e+01,8.700000e+01
CommunicationId,1125182.0,2.309002e+06,25.081896,2.308959e+06,2.308980e+06,2.309002e+06,2.309024e+06,2.309045e+06
NeighbourId,1125182.0,4.401180e+01,24.896579,2.000000e+00,2.300000e+01,4.300000e+01,6.500000e+01,8.600000e+01
NeighbourIdTwo,1125182.0,4.464984e+01,24.663753,1.000000e+00,2.400000e+01,4.400000e+01,6.600000e+01,8.700000e+01
XPos,1125182.0,5.360329e+02,340.116817,3.000000e+01,2.600000e+02,4.900000e+02,8.350000e+02,1.065000e+03
YPos,1125182.0,7.633774e+02,424.540360,1.500000e+02,4.500000e+02,7.500000e+02,1.050000e+03,1.650000e+03
wtc_GenRpm_mean,1124992.0,1.144431e+03,353.312362,6.000000e-01,9.179811e+02,1.241813e+03,1.459248e+03,1.536638e+03
wtc_MainSRpm_mean,1124992.0,1.263117e+01,3.900000,0.000000e+00,1.013165e+01,1.370614e+01,1.610599e+01,1.696051e+01
wtc_TwrHumid_mean,1124992.0,4.207970e+01,15.011888,8.196293e+00,2.975696e+01,4.019011e+01,5.397993e+01,8.648268e+01
wtc_PowerRef_endvalue,1124993.0,1.808209e+03,628.829517,0.000000e+00,1.361000e+03,2.215000e+03,2.300000e+03,2.300000e+03
wtc_PrWindSp_mean,1124992.0,8.377281e+00,3.411225,0.000000e+00,5.966530e+00,8.270673e+00,1.077281e+01,2.327238e+01
wtc_NacelPos_mean,1124991.0,1.849853e+02,93.522251,0.000000e+00,1.352548e+02,1.905208e+02,2.418631e+02,3.600000e+02
wtc_AmbieTmp_mean,1124991.0,1.381374e+01,6.982170,-8.000000e+00,9.000000e+00,1.500000e+01,1.900000e+01,3.100000e+01
wtc_GeOilTmp_mean,1124991.0,4.380707e+01,4.669669,1.200000e+01,4.100000e+01,4.413965e+01,4.702580e+01,5.669942e+01
wtc_HubTemp_mean,1124991.0,1.853124e+01,6.342129,-4.000000e+00,1.400000e+01,1.986738e+01,2.300000e+01,3.400000e+01
wtc_NacelTmp_mean,1124991.0,2.166074e+01,5.892337,-1.000000e+00,1.800000e+01,2.200000e+01,2.600000e+01,4.000000e+01
wtc_ConvWTmp_mean,1124992.0,3.153223e+01,3.604675,1.895848e+00,2.995549e+01,3.008518e+01,3.186341e+01,2.000000e+02
wtc_HydOilTm_mean,1124991.0,3.072257e+01,2.602827,0.000000e+00,3.006192e+01,3.033930e+01,3.095173e+01,5.300000e+01
wtc_MainBTmp_mean,1124991.0,3.928511e+01,5.536815,8.000000e+00,3.600000e+01,4.000000e+01,4.300000e+01,5.100000e+01
wtc_ScInOper_timeon,1124991.0,5.579990e+02,145.972517,0.000000e+00,6.000000e+02,6.000000e+02,6.000000e+02,6.000000e+02
Code,1124210.0,3.206534e+02,3420.381158,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,6.410100e+04

In [54]:
# Create alarm category
df['alarm_category'] = ''
df['alarm_category'][df['Fault Type'] == '1'] = 'Fault'
df['alarm_category'][(df['Fault Type'] == 'W') & (df['Code'] == 0)] = 'SystemOK'
df['alarm_category'][(df['Fault Type'] == 'W') & (df['Code'] != 0)] = 'Warning'

df['MainBearingFault'] = 0
df['MainBearingFault'][df['Code'] == 64038] = 1 # Main bearing temp. too high

df['Available'] = 0
df['Available'][df['wtc_ScInOper_timeon'] == 600] = 1 # turbine available for full 10 mins

wtc_PowerRef_endvalue

C:\Users\caseym\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\caseym\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Users\caseym\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Users\caseym\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\caseym\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()

In [51]:
df['MainBearingFault'].value_counts()

0    1125182
Name: MainBearingFault, dtype: int64

In [52]:
MB_alarms = df.groupby('Name')['MainBearingFault'].sum()
MB_alarms

TimeStamp
2017-01-02 15:30:00    12959
2017-01-02 15:30:00    12950
2017-01-02 15:30:00    12934
2017-01-02 15:30:00    12933
2017-01-02 15:30:00    12934
2017-01-02 15:30:00    12934
2017-01-02 15:30:00    12836
2017-01-02 15:30:00    12901
2017-01-02 15:30:00    15395
2017-01-02 15:30:00    12968
2017-01-02 15:30:00    12759
2017-01-02 15:30:00    12879
2017-01-02 15:30:00    12962
2017-01-02 15:30:00    13039
2017-01-02 15:30:00    12931
2017-01-02 15:30:00    12931
2017-01-02 15:30:00    12929
2017-01-02 15:30:00    12895
2017-01-02 15:30:00    12931
2017-01-02 15:30:00    12911
2017-01-02 15:30:00    12929
2017-01-02 15:30:00    12932
2017-01-02 15:40:00    12889
2017-01-02 15:40:00    12959
2017-01-02 15:40:00    12722
2017-01-02 15:40:00    12935
2017-01-02 15:40:00    12937
2017-01-02 15:40:00    12933
2017-01-02 15:40:00    12934
2017-01-02 15:40:00    12865
                       ...
2017-02-24 02:00:00    12961
2017-02-24 02:00:00    12931
2017-02-24 02:00:00    12915
2017-02-24 02:00:00    12932
2017-02-24 02:00:00    12937
2017-02-24 02:00:00    12932
2017-02-24 02:00:00    12807
2017-02-24 02:00:00    12968
2017-02-24 02:10:00    12163
2017-02-24 02:10:00    12920
2017-02-24 02:00:00    12934
2017-02-24 02:00:00    12934
2017-02-24 02:00:00    12901
2017-02-24 02:00:00    12968
2017-02-24 02:00:00    12888
2017-02-24 02:00:00    12879
2017-02-24 02:00:00    12962
2017-02-24 02:00:00    13039
2017-02-24 02:00:00    12936
2017-02-24 02:00:00    12931
2017-02-24 02:00:00    12929
2017-02-24 02:00:00    12895
2017-02-24 02:00:00    12932
2017-02-24 02:00:00    12911
2017-02-24 02:00:00    12929
2017-02-24 02:10:00    13063
2017-02-24 02:00:00    12935
2017-02-24 02:00:00    12932
2017-02-24 02:10:00    12889
2017-02-24 02:10:00    12959
Name: MainBearingFault, Length: 1125182, dtype: int64

In [34]:
alarms = df.groupby('Name')['Description'].count()
alarms

Name
A001    12902
A002    13059
T001    12886
T002    12142
T003    12930
T004    12951
T005    12916
T006    12657
T007    12948
T008    12720
T009    12928
T010    12916
T011    12921
T012    13038
T013    12837
T014    12936
T015    12862
T016    12872
T017    12931
T018    13026
T019    12918
T020    12932
T021    12912
T022    12923
T023    12824
T024    12930
T032    12966
T033    12834
T034    12842
T035    12953
        ...
T071    12649
T072    12902
T073    12931
T074    12921
T075    12912
T076    12913
T077    12930
T078    12868
T079    12585
T080    12831
T081    12927
T082    12927
T083    12878
T084    12926
T085    12909
T086    12930
T087    13020
T088    12929
T089    12820
T090    12930
T091    12805
T092    12920
T093    12907
T094    12929
T095    12932
T096    12928
T097    12932
T098    12964
T099    12930
T100    12929
Name: Description, Length: 87, dtype: int64

In [113]:
turbines = ['T003','T009','T014','T015','T022','T056','T071']
df2 = df.loc[df['Name'].isin(turbines)]

# One hot encoding of the alarm variable

In [45]:
from sklearn.preprocessing import OneHotEncoder

#How many alarm types are there?
print("There are " +  str(len(alarms["Code"].unique())) + " unique alarms in the dataset")
alarms["Code"].unique()

#This could be to many alarms... we may want to pair this down. It could be too much for our purposes

There are 316 unique alarms in the dataset

array([50950, 50100,  3130,   115,    25,   111,    20, 10105,    29,
         142,    67,    68,    69,    62,    92, 10400,   138, 50101,
         127,   140,   139,    54,    58,  8217,    56,   145, 50102,
          27,  1020,  1022,  1001, 50000, 50001,  1005, 13902, 17083,
       13900,     2,     7,    18,     8,  7111,    61,    59,  3127,
         113,    87,  3406,    89,  3207,  3128,   114,  3407,  3208,
       10100,  3126,   112,  3206,  3405,  1003, 17235, 63025,  1012,
        4300,  2124,    40,  9304,  4112,  3203,  3205,  3204,  9303,
        8186,  8184, 50200,  4111, 13319, 13320, 13317, 13314, 13309,
       13311,  1112, 13315, 13301,   134,  3122,  7106,   110, 13150,
       13302, 13303, 18212, 17055, 17027,    76, 63038,    28,    86,
        1140,  5110,  1018,  5111,  5112,  5113, 13214,    48,  1023,
       50008,  1025, 63412, 17065, 64066, 13121, 17058,  8000,    30,
        7101,  3421, 17011, 63210, 63211, 63204, 63209,  3118,    13,
       17107,    14,  3422,  6101, 13325, 18216,  4103, 17014, 10115,
        7100,  9101,  9111, 63300, 63036,  9306,    88,  1015,  3404,
        4200,    75, 17268, 10401, 10127,  7110,  3123,  8108,    65,
          60, 13136,  5122, 13140, 13106, 63004, 63003, 50201,  5104,
       63001,     9, 64101, 63005,  3125, 17064,  2260,    66,  8188,
       63302, 63303, 63304, 63305, 63308, 63310, 63205, 63208, 63206,
       63217, 63207, 63219,  1024, 71002,  2261,  3124,  3103,  3104,
        3105,  3140,  1007, 71001,  1017,  4125,  4109,  4110,  6102,
        1021, 50954,  2700, 17085, 17068, 17086, 17087,   123,  2200,
       17054, 18010, 18051, 18078, 18011, 18205, 18217, 18210,  3149,
        1141,  8110,  8187,  8160,  8171,  8173,  4306,  4307,  1010,
       10104,  7103, 63410, 63000,  8185,  8155,  3197,  3201, 63309,
        4123,  4121,  4122,  4124, 13219,  6100,  4104,  4108,  4107,
        4106,  4105,  4102,  4101, 64001, 17069,  3173,  7102,  3171,
        8162,  3218,  7108, 17043,  3412, 63124, 63026,  7104,  1008,
       50901, 51104, 63311, 63501, 63400,  1800,   122, 18208, 18029,
       18040,  3116, 17071, 64111, 64038,  5105,  1156, 63174,  8116,
       63502, 63202, 63216, 63203, 13217,  1004, 63016,  8114,  9105,
        1124, 18014,  4114, 64000,  8170, 17039,  3413, 17040, 17220,
       17029,  8172,  3200, 63201,  3217,  3100,  3172,  7105,  3120,
        3144,  3145,  3146,  3131,  3132,  3148,  1026, 13294,  8140,
         102])

In [5]:
 from sklearn.cross_validation import train_test_split

C:\Users\Casiano\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)